// import Footer from "./components/Footer";
// import Header from "./components/Header";
// import "./globals.css";

// export const metadata = {
//   title: "Hala Yachts",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`antialiased`}>
//         <Header />
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }
import "./globals.css";

export const metadata = {
  title: "Hala Yachts - Luxury Yacht Experiences",
  description: "Experience luxury yachting with Hala Yachts. Subscribe to our newsletter for exclusive updates.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}